In [10]:
import pandas as pd
from pathlib import Path

RAW_PATH = Path("../Raw/traffic_accidents_zh_2011_2025.csv")
PROCESSED_PATH = Path("../Processed")
OUTPUT_FILE = PROCESSED_PATH / "traffic_accidents_zh_clean.csv"

df = pd.read_csv(RAW_PATH)

df.shape

(226786, 37)

In [11]:
display(df.head())
display(df.columns.tolist())
df.info()

,AccidentUID,AccidentType,AccidentType_de,AccidentType_fr,AccidentType_it,AccidentType_en,AccidentSeverityCategory,AccidentSeverityCategory_de,AccidentSeverityCategory_fr,AccidentSeverityCategory_it,...,AccidentMonth_fr,AccidentMonth_it,AccidentMonth_en,AccidentWeekDay,AccidentWeekDay_de,AccidentWeekDay_fr,AccidentWeekDay_it,AccidentWeekDay_en,AccidentHour,AccidentHour_text
0,9FC2212663A3E0F0E0430A865E33E0F0,at7,Parkierunfall,accident en parquant,Incidente nel parcheggiare,Accident when parking,as4,Unfall mit Sachschaden,accident avec dommages matériels,Incidente con danni materiali,...,janvier,Gennaio,January,aw403,Mittwoch,mercredi,Mercoledì,Wednesday,10.0,10h-11h
1,9FC2F14A65700050E0430A865E330050,at4,Einbiegeunfall,accident en s'engageant sur une route,Incidente nell’immettersi in una strada,Accident when turning-into main road,as4,Unfall mit Sachschaden,accident avec dommages matériels,Incidente con danni materiali,...,janvier,Gennaio,January,aw405,Freitag,vendredi,Venerdì,Friday,14.0,14h-15h
2,9FC2F14A65F30050E0430A865E330050,at3,Abbiegeunfall,accident en quittant une route,Incidente nello svoltare,Accident when turning left or right,as3,Unfall mit Leichtverletzten,accident avec blessés légers,Incidente con feriti leggeri,...,janvier,Gennaio,January,aw401,Montag,lundi,Lunedí,Monday,8.0,08h-09h
3,9FC2F14A672A0050E0430A865E330050,at8,Fussgängerunfall,accident impliquant des piétons,Incidente con pedoni,Accident involving pedestrian(s),as3,Unfall mit Leichtverletzten,accident avec blessés légers,Incidente con feriti leggeri,...,janvier,Gennaio,January,aw402,Dienstag,mardi,Martedì,Tuesday,18.0,18h-19h
4,9FC2F14A694B0050E0430A865E330050,at2,Auffahrunfall,accident par tamponnement,Incidente di tamponamento,Accident with rear-end collision,as3,Unfall mit Leichtverletzten,accident avec blessés légers,Incidente con feriti leggeri,...,janvier,Gennaio,January,aw406,Samstag,samedi,Sabato,Saturday,9.0,09h-10h

['AccidentUID',
 'AccidentType',
 'AccidentType_de',
 'AccidentType_fr',
 'AccidentType_it',
 'AccidentType_en',
 'AccidentSeverityCategory',
 'AccidentSeverityCategory_de',
 'AccidentSeverityCategory_fr',
 'AccidentSeverityCategory_it',
 'AccidentSeverityCategory_en',
 'AccidentInvolvingPedestrian',
 'AccidentInvolvingBicycle',
 'AccidentInvolvingMotorcycle',
 'RoadType',
 'RoadType_de',
 'RoadType_fr',
 'RoadType_it',
 'RoadType_en',
 'AccidentLocation_CHLV95_E',
 'AccidentLocation_CHLV95_N',
 'CantonCode',
 'MunicipalityCode_Aktuell',
 'MunicipalityCode_AccidentYear',
 'AccidentYear',
 'AccidentMonth',
 'AccidentMonth_de',
 'AccidentMonth_fr',
 'AccidentMonth_it',
 'AccidentMonth_en',
 'AccidentWeekDay',
 'AccidentWeekDay_de',
 'AccidentWeekDay_fr',
 'AccidentWeekDay_it',
 'AccidentWeekDay_en',
 'AccidentHour',
 'AccidentHour_text']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226786 entries, 0 to 226785
Data columns (total 37 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   AccidentUID                    226786 non-null  object
 1   AccidentType                   226786 non-null  object
 2   AccidentType_de                226786 non-null  object
 3   AccidentType_fr                226786 non-null  object
 4   AccidentType_it                226786 non-null  object
 5   AccidentType_en                226786 non-null  object
 6   AccidentSeverityCategory       226786 non-null  object
 7   AccidentSeverityCategory_de    226786 non-null  object
 8   AccidentSeverityCategory_fr    226786 non-null  object
 9   AccidentSeverityCategory_it    226786 non-null  object
 10  AccidentSeverityCategory_en    226786 non-null  object
 11  AccidentInvolvingPedestrian    226786 non-null  bool
 12  AccidentInvolvingBicycle       226786 non-null  bool
 13  AccidentInvolvingMotorcycle    226786 non-null  bool
 14  RoadType                       226786 non-null  object
 15  RoadType_de                    226786 non-null  object
 16  RoadType_fr                    226786 non-null  object
 17  RoadType_it                    226786 non-null  object
 18  RoadType_en                    226786 non-null  object
 19  AccidentLocation_CHLV95_E      226786 non-null  int64
 20  AccidentLocation_CHLV95_N      226786 non-null  int64
 21  CantonCode                     226786 non-null  object
 22  MunicipalityCode_Aktuell       226786 non-null  int64
 23  MunicipalityCode_AccidentYear  226786 non-null  int64
 24  AccidentYear                   226786 non-null  int64
 25  AccidentMonth                  226786 non-null  int64
 26  AccidentMonth_de               226786 non-null  object
 27  AccidentMonth_fr               226786 non-null  object
 28  AccidentMonth_it               226786 non-null  object
 29  AccidentMonth_en               226786 non-null  object
 30  AccidentWeekDay                226786 non-null  object
 31  AccidentWeekDay_de             226786 non-null  object
 32  AccidentWeekDay_fr             226786 non-null  object
 33  AccidentWeekDay_it             226786 non-null  object
 34  AccidentWeekDay_en             226786 non-null  object
 35  AccidentHour                   224930 non-null  float64
 36  AccidentHour_text              224930 non-null  object
dtypes: bool(3), float64(1), int64(6), object(27)
memory usage: 59.5+ MB

In [12]:
print(f"Number of observations: {df.shape[0]}")
print(f"Number of features: {df.shape[1]}")

print("\nData types:")
display(df.dtypes.value_counts())

Number of observations: 226786
Number of features: 37

Data types:

object     27
int64       6
bool        3
float64     1
Name: count, dtype: int64

In [13]:
missing = (
    df.isna()
    .sum()
    .sort_values(ascending=False)
    .to_frame("missing_count")
)

missing["missing_percentage"] = (
    missing["missing_count"] / len(df) * 100
).round(2)

missing.head(15)

                               missing_count  missing_percentage
AccidentHour_text                       1856                0.82
AccidentHour                            1856                0.82
AccidentMonth_fr                           0                0.00
CantonCode                                 0                0.00
MunicipalityCode_Aktuell                   0                0.00
MunicipalityCode_AccidentYear              0                0.00
AccidentYear                               0                0.00
AccidentMonth                              0                0.00
AccidentMonth_de                           0                0.00
AccidentMonth_it                           0                0.00
AccidentLocation_CHLV95_E                  0                0.00
AccidentMonth_en                           0                0.00
AccidentWeekDay                            0                0.00
AccidentWeekDay_de                         0                0.00
AccidentWeekDay_fr                         0                0.00

In [14]:
display(df["AccidentYear"].value_counts().sort_index())
display(df["AccidentSeverityCategory_en"].value_counts())
display(df["AccidentType_en"].value_counts())
display(df["RoadType_en"].value_counts())
display(df["AccidentWeekDay_en"].value_counts())
display(df["AccidentHour"].value_counts().sort_index())

AccidentYear
2011    13258
2012    13273
2013    13298
2014    13066
2015    14395
2016    16197
2017    16824
2018    16502
2019    16247
2020    14911
2021    15724
2022    16457
2023    16167
2024    15372
2025    15095
Name: count, dtype: int64

AccidentSeverityCategory_en
Accident with property damage    177389
Accident with light injuries      40793
Accident with severe injuries      8188
Accident with fatalities            416
Name: count, dtype: int64

AccidentType_en
Accident with skidding or self-accident       77662
Accident with rear-end collision              42473
Accident when parking                         39239
Accident when overtaking or changing lanes    18978
Accident when turning-into main road          15741
Accident when turning left or right            9552
Accident involving pedestrian(s)               7364
Accident when crossing the lane(s)             6099
Accident involving animal(s)                   4269
Accident with head-on collision                2803
Other                                          2606
Name: count, dtype: int64

RoadType_en
Minor road                    115549
Principal road                 57342
Motorway                       31131
Other                          20126
Expressway                      2174
Motorway side installation       464
Name: count, dtype: int64

AccidentWeekDay_en
Friday       37566
Wednesday    35128
Thursday     35061
Tuesday      33922
Monday       32558
Saturday     30662
Sunday       21889
Name: count, dtype: int64

AccidentHour
0.0      3314
1.0      2352
2.0      1927
3.0      1723
4.0      1971
5.0      3016
6.0      7638
7.0     11214
8.0     11808
9.0     10701
10.0    12019
11.0    13422
12.0    13479
13.0    13485
14.0    14781
15.0    15541
16.0    18063
17.0    20340
18.0    15696
19.0    10113
20.0     7190
21.0     5655
22.0     5318
23.0     4164
Name: count, dtype: int64

In [15]:
accidents_per_year = (
    df["AccidentYear"]
    .value_counts()
    .sort_index()
    .to_frame("accident_count")
)

accidents_per_year

              accident_count
AccidentYear
2011                   13258
2012                   13273
2013                   13298
2014                   13066
2015                   14395
2016                   16197
2017                   16824
2018                   16502
2019                   16247
2020                   14911
2021                   15724
2022                   16457
2023                   16167
2024                   15372
2025                   15095

In [16]:
selected_columns = [
    "AccidentUID",
    "AccidentType_en",
    "AccidentSeverityCategory_en",
    "RoadType_en",
    "AccidentInvolvingPedestrian",
    "AccidentInvolvingBicycle",
    "AccidentInvolvingMotorcycle",
    "AccidentLocation_CHLV95_E",
    "AccidentLocation_CHLV95_N",
    "MunicipalityCode_Aktuell",
    "AccidentYear",
    "AccidentMonth",
    "AccidentMonth_en",
    "AccidentWeekDay_en",
    "AccidentHour",
    "AccidentHour_text"
]

df_selected = df[selected_columns].copy()

PROCESSED_PATH.mkdir(parents=True, exist_ok=True)

df_selected.to_csv(OUTPUT_FILE, index=False)

OUTPUT_FILE

df_selected.shape
df_selected.head()

,AccidentUID,AccidentType_en,AccidentSeverityCategory_en,RoadType_en,AccidentInvolvingPedestrian,AccidentInvolvingBicycle,AccidentInvolvingMotorcycle,AccidentLocation_CHLV95_E,AccidentLocation_CHLV95_N,MunicipalityCode_Aktuell,AccidentYear,AccidentMonth,AccidentMonth_en,AccidentWeekDay_en,AccidentHour,AccidentHour_text
0,9FC2212663A3E0F0E0430A865E33E0F0,Accident when parking,Accident with property damage,Other,False,False,False,2683598,1253507,261,2011,1,January,Wednesday,10.0,10h-11h
1,9FC2F14A65700050E0430A865E330050,Accident when turning-into main road,Accident with property damage,Minor road,False,False,False,2680708,1252618,261,2011,1,January,Friday,14.0,14h-15h
2,9FC2F14A65F30050E0430A865E330050,Accident when turning left or right,Accident with light injuries,Minor road,False,True,False,2681179,1247560,261,2011,1,January,Monday,8.0,08h-09h
3,9FC2F14A672A0050E0430A865E330050,Accident involving pedestrian(s),Accident with light injuries,Principal road,True,False,False,2679811,1246849,261,2011,1,January,Tuesday,18.0,18h-19h
4,9FC2F14A694B0050E0430A865E330050,Accident with rear-end collision,Accident with light injuries,Minor road,False,False,False,2682789,1247449,261,2011,1,January,Saturday,9.0,09h-10h